export const ipc = {
  snapshot: 'grafter:snapshot',
  commandLog: 'grafter:command-log',
  chooseProject: 'grafter:choose-project',
  removeProject: 'grafter:remove-project',
  refresh: 'grafter:refresh',
  listBranches: 'grafter:list-branches',
  suggestWorktreePath: 'grafter:suggest-worktree-path',
  createWorktree: 'grafter:create-worktree',
  prepareRemove: 'grafter:prepare-remove',
  approveCommand: 'grafter:approve-command',
  rejectCommand: 'grafter:reject-command',
  worktreeDetails: 'grafter:worktree-details',
  worktreeStatus: 'grafter:worktree-status',
  updateSettings: 'grafter:update-settings',
  updateProjectSetup: 'grafter:update-project-setup',
  openWorktreeDirectory: 'grafter:open-worktree-directory',
  openWorktreeInEditor: 'grafter:open-worktree-in-editor',
  openExternal: 'grafter:open-external',
  commandUpdate: 'grafter:command-update',
} as const;
